/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LIBRASOffice;

import com.sun.star.comp.helper.BootstrapException;
import com.sun.star.frame.XComponentLoader;
import com.sun.star.frame.XDesktop;
import com.sun.star.frame.XDispatchHelper;
import com.sun.star.frame.XDispatchProvider;
import com.sun.star.frame.XFrame;
import com.sun.star.frame.XTitle;
import com.sun.star.lang.XComponent;
import com.sun.star.lang.XMultiComponentFactory;
import com.sun.star.uno.Exception;
import com.sun.star.uno.UnoRuntime;
import com.sun.star.uno.XComponentContext;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author jonathanelias
 */
public class LIBRASOffice extends javax.swing.JFrame {
    /**
     * Creates new form LIBRASOffice
     */
    public LIBRASOffice() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        REFAZER = new javax.swing.JButton();
        VOLTAR = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ABRIR = new javax.swing.JButton();
        NOVO = new javax.swing.JButton();
        PDF = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        IMPRIMIR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        COPIAR = new javax.swing.JButton();
        COLAR = new javax.swing.JButton();
        CORTAR = new javax.swing.JButton();
        PROCURAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SOMAR = new javax.swing.JButton();

        jFrame1.setLocation(new java.awt.Point(0, 0));
        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(550, 520));
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrame1WindowActivated(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 640, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 480, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIF240/OPCAO_240.gif"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        REFAZER.setText("Refazer");
        REFAZER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REFAZERMouseEntered(evt);
            }
        });
        REFAZER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFAZERActionPerformed(evt);
            }
        });
        getContentPane().add(REFAZER, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 460, -1, -1));

        VOLTAR.setText("Voltar");
        VOLTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VOLTARMouseEntered(evt);
            }
        });
        VOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTARActionPerformed(evt);
            }
        });
        getContentPane().add(VOLTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 460, -1, -1));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        ABRIR.setText("Abrir Documento");
        ABRIR.setToolTipText("CTRL + O");
        ABRIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ABRIRMouseEntered(evt);
            }
        });
        ABRIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABRIRActionPerformed(evt);
            }
        });

        NOVO.setText("Novo Documento");
        NOVO.setToolTipText("CTRL + N");
        NOVO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NOVO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NOVOMouseEntered(evt);
            }
        });
        NOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOVOActionPerformed(evt);
            }
        });

        PDF.setText("Gerar PDF");
        PDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PDFMouseEntered(evt);
            }
        });
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });

        GUARDAR.setText("Guardar Documento");
        GUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GUARDARMouseEntered(evt);
            }
        });
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });

        IMPRIMIR.setText("Imprimir Documento");
        IMPRIMIR.setToolTipText("CTRL + P");
        IMPRIMIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IMPRIMIRMouseEntered(evt);
            }
        });
        IMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMPRIMIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUARDAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ABRIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IMPRIMIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NOVO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(NOVO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ABRIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(GUARDAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IMPRIMIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PDF)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Documento", null, jPanel1, "");

        COPIAR.setText("Copiar Texto");
        COPIAR.setToolTipText("CTRL + C");
        COPIAR.setMaximumSize(new java.awt.Dimension(153, 25));
        COPIAR.setMinimumSize(new java.awt.Dimension(153, 25));
        COPIAR.setPreferredSize(new java.awt.Dimension(153, 25));
        COPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                COPIARMouseEntered(evt);
            }
        });
        COPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COPIARActionPerformed(evt);
            }
        });

        COLAR.setText("Colar Texto");
        COLAR.setToolTipText("CTRL + V");
        COLAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                COLARMouseEntered(evt);
            }
        });
        COLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLARActionPerformed(evt);
            }
        });

        CORTAR.setText("Cortar Texto");
        CORTAR.setToolTipText("CTRL + X");
        CORTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CORTARMouseEntered(evt);
            }
        });
        CORTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CORTARActionPerformed(evt);
            }
        });

        PROCURAR.setText("Procurar Texto");
        PROCURAR.setToolTipText("CTRL + F");
        PROCURAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROCURARMouseEntered(evt);
            }
        });
        PROCURAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCURARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(COPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(CORTAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(COLAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PROCURAR, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(COPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CORTAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(COLAR)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(PROCURAR)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Texto", jPanel3);

        SOMAR.setText("Inserir Soma");
        SOMAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SOMARMouseEntered(evt);
            }
        });
        SOMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOMARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SOMAR, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SOMAR)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fórmula", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 290, -1));
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        System.out.println(evt.getXOnScreen());
    }//GEN-LAST:event_formMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{ xDesk.terminate(); }
        finally { System.exit(0); }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        System.out.println(evt.toString());
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Dimension scSize = Toolkit.getDefaultToolkit().getScreenSize();
        //evt.getWindow().setSize(scSize.width, 275);
        //this.setLocation(0, 0);
    }//GEN-LAST:event_formWindowActivated

    private void VOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:Undo", "", 0, null);
    }//GEN-LAST:event_VOLTARActionPerformed

    private void REFAZERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFAZERActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:Redo", "", 0, null);
    }//GEN-LAST:event_REFAZERActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.out.println(evt.toString());
       jLabel2.setIcon(new ImageIcon(getClass().getResource("/GIF480/"+currOpt+"_480.gif")));
       jFrame1.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jFrame1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowActivated
        Dimension scSize = Toolkit.getDefaultToolkit().getScreenSize();
        jFrame1.setLocation(scSize.width/2-jFrame1.getSize().width/2, scSize.height/2-jFrame1.getSize().height);
    }//GEN-LAST:event_jFrame1WindowActivated

    private void VOLTARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTARMouseEntered
        currOpt = "VOLTAR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_VOLTARMouseEntered

    private void REFAZERMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFAZERMouseEntered
        currOpt = "REFAZER";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_REFAZERMouseEntered

    private void SOMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOMARActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:AutoSum", "", 0, null);
    }//GEN-LAST:event_SOMARActionPerformed

    private void SOMARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOMARMouseEntered
        currOpt = "SOMAR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_SOMARMouseEntered

    private void PROCURARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCURARActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:SearchDialog", "", 0, null);
    }//GEN-LAST:event_PROCURARActionPerformed

    private void PROCURARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROCURARMouseEntered
        currOpt = "PROCURAR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_PROCURARMouseEntered

    private void CORTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CORTARActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:Cut", "", 0, null);
    }//GEN-LAST:event_CORTARActionPerformed

    private void CORTARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CORTARMouseEntered
        currOpt = "CORTAR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_CORTARMouseEntered

    private void COLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLARActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:Paste", "", 0, null);
    }//GEN-LAST:event_COLARActionPerformed

    private void COLARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COLARMouseEntered
        currOpt = "COLAR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_COLARMouseEntered

    private void COPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COPIARActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:Copy", "", 0, null);
    }//GEN-LAST:event_COPIARActionPerformed

    private void COPIARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COPIARMouseEntered
        currOpt = "COPIAR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_COPIARMouseEntered

    private void IMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMPRIMIRActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:Print", "", 0, null);
    }//GEN-LAST:event_IMPRIMIRActionPerformed

    private void IMPRIMIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMPRIMIRMouseEntered
        currOpt = "IMPRIMIR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_IMPRIMIRMouseEntered

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:SaveAs", "", 0, null);
    }//GEN-LAST:event_GUARDARActionPerformed

    private void GUARDARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUARDARMouseEntered
        currOpt = "GUARDAR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_GUARDARMouseEntered

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:ExportDirectToPDF", "", 0, null);
    }//GEN-LAST:event_PDFActionPerformed

    private void PDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDFMouseEntered
        currOpt = "PDF";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_PDFMouseEntered

    private void NOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOVOActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:NewDoc", "", 0, null);
    }//GEN-LAST:event_NOVOActionPerformed

    private void NOVOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOVOMouseEntered
        currOpt = "NOVO";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_NOVOMouseEntered

    private void ABRIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABRIRActionPerformed
        xDHelper.executeDispatch(xDProver, ".uno:OpenFromCalc", "", 0, null);
    }//GEN-LAST:event_ABRIRActionPerformed

    private void ABRIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABRIRMouseEntered
        currOpt = "ABRIR";
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
    }//GEN-LAST:event_ABRIRMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws BootstrapException, Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LIBRASOffice().setVisible(true);             
            }
        });
        System.out.println(System.getProperty("user.dir"));

        XComponentContext xCxt = com.sun.star.comp.helper.Bootstrap.bootstrap();
        //XComponentContext xCxt = BootstrapSocketConnector.bootstrap("C:/Program Files (x86)/LibreOffice 4/program/");

        XMultiComponentFactory xSMng = xCxt.getServiceManager();

        Object desk = xSMng.createInstanceWithContext("com.sun.star.frame.Desktop", xCxt);
        xDesk = UnoRuntime.queryInterface(XDesktop.class, desk);
                
        XComponentLoader xCLoader =  (XComponentLoader)UnoRuntime.queryInterface(XComponentLoader.class, desk);
                
        XComponent xDoc = xCLoader.loadComponentFromURL("private:factory/scalc", "_blank", 0, null);

        XFrame dFrame = xDesk.getCurrentFrame();
        while (dFrame == null) dFrame = xDesk.getCurrentFrame();
                
        XTitle wTitle = UnoRuntime.queryInterface(XTitle.class, dFrame);
        wTitle.setTitle(wTitle.getTitle().replace("Libre", "LIBRAS"));

        Object disper = xSMng.createInstanceWithContext("com.sun.star.frame.DispatchHelper", xCxt);
        xDHelper = UnoRuntime.queryInterface(XDispatchHelper.class, disper);
        xDProver = UnoRuntime.queryInterface(XDispatchProvider.class, dFrame);
                
        //xDHelper.executeDispatch(xDProver, ".uno:SaveAs", "", 0, null);
        xTL xTL0 = new xTL(); 
        xDesk.addTerminateListener(xTL0);
        synchronized(xTL0){
            try { xTL0.wait(); }
            catch (InterruptedException ex) {
                Logger.getLogger(LIBRASOffice.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABRIR;
    private javax.swing.JButton COLAR;
    private javax.swing.JButton COPIAR;
    private javax.swing.JButton CORTAR;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JButton IMPRIMIR;
    private javax.swing.JButton NOVO;
    private javax.swing.JButton PDF;
    private javax.swing.JButton PROCURAR;
    private javax.swing.JButton REFAZER;
    private javax.swing.JButton SOMAR;
    private javax.swing.JButton VOLTAR;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    private static XDesktop xDesk;
    private static XDispatchHelper xDHelper;
    private static XDispatchProvider xDProver;
    private String currOpt = "OPCAO";
    private Dimension scSize = Toolkit.getDefaultToolkit().getScreenSize();
}