/*
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package LIBRASOffice;


import com.sun.star.beans.PropertyValue;
import com.sun.star.comp.helper.BootstrapException;
import com.sun.star.frame.XComponentLoader;
import com.sun.star.frame.XDesktop;
import com.sun.star.frame.XDispatchHelper;
import com.sun.star.frame.XDispatchProvider;
import com.sun.star.frame.XFrame;
import com.sun.star.frame.XTitle;
import com.sun.star.lang.XComponent;
import com.sun.star.lang.XMultiComponentFactory;
import com.sun.star.uno.Exception;
import com.sun.star.uno.UnoRuntime;
import com.sun.star.uno.XComponentContext;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author jonathan_elias_costa
 * @author eduardo_castanho
 */
public class LIBRASOffice extends javax.swing.JFrame {
    /**
     * Creates new form LIBRASOffice
     */
    public LIBRASOffice() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        REFAZER = new javax.swing.JButton();
        VOLTAR = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ABRIR = new javax.swing.JButton();
        NOVO = new javax.swing.JButton();
        PDF = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        IMPRIMIR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        COPIAR = new javax.swing.JButton();
        COLAR = new javax.swing.JButton();
        CORTAR = new javax.swing.JButton();
        PROCURAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SOMAR = new javax.swing.JButton();
        SUBTRACAO = new javax.swing.JButton();
        DIVISAO = new javax.swing.JButton();
        MULTIPLICACAO = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        DINHEIRO = new javax.swing.JButton();
        PORCENTAGEM = new javax.swing.JButton();
        NUMERO = new javax.swing.JButton();
        DATA = new javax.swing.JButton();
        CampoInicial = new javax.swing.JPanel();
        NextInicial = new javax.swing.JButton();
        LabelInicial = new javax.swing.JLabel();
        Inicial = new javax.swing.JTextField();
        CampoFinal = new javax.swing.JPanel();
        NextFinal = new javax.swing.JButton();
        LabelFinal = new javax.swing.JLabel();
        Final = new javax.swing.JTextField();
        CampoResultado = new javax.swing.JPanel();
        NextResultado = new javax.swing.JButton();
        LabelResultado = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();

        jFrame1.setLocation(new java.awt.Point(0, 0));
        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(550, 520));
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrame1WindowActivated(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 640, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 480, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIF240/OPCAO_240.gif"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        REFAZER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/redo.png"))); // NOI18N
        REFAZER.setText("Refazer");
        REFAZER.setToolTipText("CTRL + Y");
        REFAZER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REFAZERMouseClicked(evt);
            }
        });
        getContentPane().add(REFAZER, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 460, -1, -1));

        VOLTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/undo.png"))); // NOI18N
        VOLTAR.setText("Voltar");
        VOLTAR.setToolTipText("CTRL + X");
        VOLTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTARMouseClicked(evt);
            }
        });
        getContentPane().add(VOLTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 460, -1, -1));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        ABRIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/open.png"))); // NOI18N
        ABRIR.setText("Abrir Documento");
        ABRIR.setToolTipText("CTRL + O");
        ABRIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ABRIRMouseClicked(evt);
            }
        });

        NOVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/new.png"))); // NOI18N
        NOVO.setText("Novo Documento");
        NOVO.setToolTipText("CTRL + N");
        NOVO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOVOMouseClicked(evt);
            }
        });

        PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/pdf.png"))); // NOI18N
        PDF.setText("Gerar PDF");
        PDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PDFMouseClicked(evt);
            }
        });

        GUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/save.png"))); // NOI18N
        GUARDAR.setText("Guardar Documento");
        GUARDAR.setToolTipText("CTRL + S");
        GUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GUARDARMouseClicked(evt);
            }
        });

        IMPRIMIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/print.png"))); // NOI18N
        IMPRIMIR.setText("Imprimir Documento");
        IMPRIMIR.setToolTipText("CTRL + P");
        IMPRIMIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMPRIMIRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GUARDAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ABRIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IMPRIMIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NOVO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(NOVO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ABRIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GUARDAR)
                .addGap(12, 12, 12)
                .addComponent(IMPRIMIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Documento", null, jPanel1, "");

        COPIAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/copy.png"))); // NOI18N
        COPIAR.setText("Copiar Texto");
        COPIAR.setToolTipText("CTRL + C");
        COPIAR.setMaximumSize(new java.awt.Dimension(153, 25));
        COPIAR.setMinimumSize(new java.awt.Dimension(153, 25));
        COPIAR.setPreferredSize(new java.awt.Dimension(153, 25));
        COPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COPIARMouseClicked(evt);
            }
        });

        COLAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/paste.png"))); // NOI18N
        COLAR.setText("Colar Texto");
        COLAR.setToolTipText("CTRL + V");
        COLAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COLARMouseClicked(evt);
            }
        });

        CORTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/cut.png"))); // NOI18N
        CORTAR.setText("Cortar Texto");
        CORTAR.setToolTipText("CTRL + X");
        CORTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CORTARMouseClicked(evt);
            }
        });

        PROCURAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/find.png"))); // NOI18N
        PROCURAR.setText("Procurar Texto");
        PROCURAR.setToolTipText("CTRL + F");
        PROCURAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROCURARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(COPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(CORTAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(COLAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PROCURAR, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(COPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CORTAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(COLAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PROCURAR)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Texto", jPanel3);

        SOMAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/sum.png"))); // NOI18N
        SOMAR.setText("Inserir Soma");
        SOMAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SOMARMouseClicked(evt);
            }
        });

        SUBTRACAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/sum.png"))); // NOI18N
        SUBTRACAO.setText("Inserir Subtração");
        SUBTRACAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUBTRACAOMouseClicked(evt);
            }
        });

        DIVISAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/sum.png"))); // NOI18N
        DIVISAO.setText("Inserir Divisão");
        DIVISAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DIVISAOMouseClicked(evt);
            }
        });

        MULTIPLICACAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/sum.png"))); // NOI18N
        MULTIPLICACAO.setText("Inserir Multiplicação");
        MULTIPLICACAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MULTIPLICACAOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SOMAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SUBTRACAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(DIVISAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MULTIPLICACAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SOMAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SUBTRACAO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DIVISAO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MULTIPLICACAO)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fórmula", jPanel2);

        DINHEIRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/currency.png"))); // NOI18N
        DINHEIRO.setText("Dinheiro");
        DINHEIRO.setToolTipText("CTRL + SHIFT + 4");
        DINHEIRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DINHEIROMouseClicked(evt);
            }
        });

        PORCENTAGEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/percent.png"))); // NOI18N
        PORCENTAGEM.setText("Porcentagem");
        PORCENTAGEM.setToolTipText("CTRL + SHIFT + 5");
        PORCENTAGEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PORCENTAGEMMouseClicked(evt);
            }
        });

        NUMERO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/decimal.png"))); // NOI18N
        NUMERO.setText("Número");
        NUMERO.setToolTipText("CTRL + SHIFT + 1");
        NUMERO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUMEROMouseClicked(evt);
            }
        });

        DATA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/date.png"))); // NOI18N
        DATA.setText("Data");
        DATA.setToolTipText("CTRL + SHIFT + 3");
        DATA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DATAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NUMERO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PORCENTAGEM, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(DATA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DINHEIRO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DINHEIRO)
                .addGap(12, 12, 12)
                .addComponent(PORCENTAGEM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NUMERO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DATA)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Número", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 290, 200));
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        NextInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIBRASOffice/next.png"))); // NOI18N
        NextInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextInicialMouseClicked(evt);
            }
        });

        LabelInicial.setText("Campo Inicial:");

        javax.swing.GroupLayout CampoInicialLayout = new javax.swing.GroupLayout(CampoInicial);
        CampoInicial.setLayout(CampoInicialLayout);
        CampoInicialLayout.setHorizontalGroup(
            CampoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoInicialLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LabelInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampoInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CampoInicialLayout.setVerticalGroup(
            CampoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampoInicialLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(CampoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelInicial)
                    .addComponent(Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(NextInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(CampoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 251, 300, 240));
        CampoInicial.setVisible(false);

        NextFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIBRASOffice/next.png"))); // NOI18N
        NextFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextFinalMouseClicked(evt);
            }
        });

        LabelFinal.setText("Campo Final:");

        javax.swing.GroupLayout CampoFinalLayout = new javax.swing.GroupLayout(CampoFinal);
        CampoFinal.setLayout(CampoFinalLayout);
        CampoFinalLayout.setHorizontalGroup(
            CampoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoFinalLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LabelFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampoFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CampoFinalLayout.setVerticalGroup(
            CampoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampoFinalLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(CampoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFinal)
                    .addComponent(Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(NextFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(CampoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 251, 300, 240));
        CampoFinal.setVisible(false);

        NextResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIBRASOffice/next.png"))); // NOI18N
        NextResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextResultadoMouseClicked(evt);
            }
        });

        LabelResultado.setText("Campo de Resultado:");

        javax.swing.GroupLayout CampoResultadoLayout = new javax.swing.GroupLayout(CampoResultado);
        CampoResultado.setLayout(CampoResultadoLayout);
        CampoResultadoLayout.setHorizontalGroup(
            CampoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoResultadoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LabelResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampoResultadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CampoResultadoLayout.setVerticalGroup(
            CampoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CampoResultadoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(CampoResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResultado)
                    .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(NextResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(CampoResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 251, 300, 240));
        CampoResultado.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        System.out.println(evt.getXOnScreen());
    }//GEN-LAST:event_formMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{ xDesk.terminate(); }
        finally { System.exit(0); }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        System.out.println(evt.toString());
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Dimension scSize = Toolkit.getDefaultToolkit().getScreenSize();
        //evt.getWindow().setSize(scSize.width, 275);
        //this.setLocation(0, 0);
    }//GEN-LAST:event_formWindowActivated

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.out.println(evt.toString());
       jLabel2.setIcon(new ImageIcon(getClass().getResource("/GIF480/"+currOpt+"_480.gif")));
       jFrame1.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jFrame1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowActivated
        Dimension scSize = Toolkit.getDefaultToolkit().getScreenSize();
        jFrame1.setLocation(scSize.width/2-jFrame1.getSize().width/2, scSize.height/2-jFrame1.getSize().height);
    }//GEN-LAST:event_jFrame1WindowActivated

    private void NOVOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOVOMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "NOVO";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:NewDoc", "", 0, null);        
    }//GEN-LAST:event_NOVOMouseClicked

    private void ABRIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABRIRMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "ABRIR";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:OpenFromCalc", "", 0, null);
    }//GEN-LAST:event_ABRIRMouseClicked

    private void GUARDARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUARDARMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "GUARDAR";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:SaveAs", "", 0, null);
    }//GEN-LAST:event_GUARDARMouseClicked

    private void IMPRIMIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMPRIMIRMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "IMPRIMIR";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:Print", "", 0, null);
    }//GEN-LAST:event_IMPRIMIRMouseClicked

    private void PDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDFMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "PDF";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:ExportDirectToPDF", "", 0, null);
    }//GEN-LAST:event_PDFMouseClicked

    private void COPIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COPIARMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "COPIAR";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else  xDHelper.executeDispatch(xDProver, ".uno:Copy", "", 0, null);
    }//GEN-LAST:event_COPIARMouseClicked

    private void CORTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CORTARMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "CORTAR";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:Cut", "", 0, null);
    }//GEN-LAST:event_CORTARMouseClicked

    private void COLARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COLARMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "COLA";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:Paste", "", 0, null);
    }//GEN-LAST:event_COLARMouseClicked

    private void PROCURARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROCURARMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "PROCURAR";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:SearchDialog", "", 0, null);
    }//GEN-LAST:event_PROCURARMouseClicked

    private void SOMARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SOMARMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "SOMA";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else AssistenteFormula();

    }//GEN-LAST:event_SOMARMouseClicked

    private void DINHEIROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DINHEIROMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "DINHEIRO";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:NumberFormatCurrency", "", 0, null);
    }//GEN-LAST:event_DINHEIROMouseClicked

    private void PORCENTAGEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PORCENTAGEMMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "PORCENTAGEM";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:NumberFormatPercent", "", 0, null);
    }//GEN-LAST:event_PORCENTAGEMMouseClicked

    private void NUMEROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUMEROMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "NUMERO";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:NumberFormatDecimal", "", 0, null);
    }//GEN-LAST:event_NUMEROMouseClicked

    private void DATAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DATAMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "DATA";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:NumberFormatDate", "", 0, null);
    }//GEN-LAST:event_DATAMouseClicked

    private void VOLTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTARMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "VOLTAR";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:Undo", "", 0, null);
    }//GEN-LAST:event_VOLTARMouseClicked

    private void REFAZERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REFAZERMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "REFAZER";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else xDHelper.executeDispatch(xDProver, ".uno:Redo", "", 0, null);
    }//GEN-LAST:event_REFAZERMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(jTabbedPane1.getSelectedIndex() == 0){
            currOpt = "DOCUMENTO";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        if(jTabbedPane1.getSelectedIndex() == 1){
            currOpt = "TEXTO";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        if(jTabbedPane1.getSelectedIndex() == 2){
            currOpt = "SOMA";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        if(jTabbedPane1.getSelectedIndex() == 3){
            currOpt = "ALTERAR_NUMERO";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void SUBTRACAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUBTRACAOMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "SUB";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else AssistenteFormula();
    }//GEN-LAST:event_SUBTRACAOMouseClicked

    private void DIVISAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIVISAOMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "DIV";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else AssistenteFormula();
    }//GEN-LAST:event_DIVISAOMouseClicked

    private void MULTIPLICACAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MULTIPLICACAOMouseClicked
        if(evt.getClickCount() == 1){
            currOpt = "MULT";
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));
        }
        else AssistenteFormula();
    }//GEN-LAST:event_MULTIPLICACAOMouseClicked

    private void NextInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextInicialMouseClicked
        if (!"".equals(Inicial.getText())) {
            CampoInicial.setVisible(false);
            CampoFinal.setVisible(true);
           jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/LOCAL_FINAL_240.gif")));
            System.out.println(Inicial.getText());
        }
    }//GEN-LAST:event_NextInicialMouseClicked

    private void NextResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextResultadoMouseClicked
        if (!"".equals(Resultado.getText())) {
            System.out.println(Resultado.getText());
            PropertyValue[] args1 = new PropertyValue[1];
            args1[0] = new PropertyValue();
            args1[0].Name = "ToPoint";
            args1[0].Value = Resultado.getText();
            xDHelper.executeDispatch(xDProver, ".uno:GoToCell", "", 0, args1);
            PropertyValue[] args2 = new PropertyValue[1];
            args2[0] = new PropertyValue();
            args2[0].Name = "StringName";
            if ("SOMA".equals(currOpt)) args2[0].Value = "=SOMA("+Inicial.getText()+":"+Final.getText()+")";
            if ("SUB".equals(currOpt)) args2[0].Value = "="+Inicial.getText()+"-"+Final.getText();
            if ("DIV".equals(currOpt)) args2[0].Value = "="+Inicial.getText()+"/"+Final.getText();
            if ("MULT".equals(currOpt)) args2[0].Value = "=MULT("+Inicial.getText()+":"+Final.getText()+")";
            xDHelper.executeDispatch(xDProver, ".uno:EnterString", "", 0, args2);
            CampoResultado.setVisible(false);
            jTabbedPane1.setVisible(true);
            REFAZER.setVisible(true);
            VOLTAR.setVisible(true);
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/"+currOpt+"_240.gif")));        
        }
    }//GEN-LAST:event_NextResultadoMouseClicked

    private void NextFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextFinalMouseClicked
        if (!"".equals(Final.getText())) {
            CampoFinal.setVisible(false);
            CampoResultado.setVisible(true);
           jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/LOCAL_RESULTADO_240.gif")));
            System.out.println(Final.getText());
        }
    }//GEN-LAST:event_NextFinalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws BootstrapException, Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LIBRASOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LIBRASOffice().setVisible(true);             
            }
        });
        /*DEBUG*/ System.out.println(System.getProperty("user.dir"));
        
        /** Inicializar instância local do LibreOffice (bootstrap) a partir do executável soffice encontrado na PATH do sistema, obtendo um contexto global
         *  Outra opção seria utilizar a biblioteca BootstrapSocketConnector para se conectar a uma instância do LibreOffice já em execução com executável encontrado no PATH informado    
         *  REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/FirstSteps/First_Contact#Getting_Started 
         *  REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/ProUNO/Java/Transparent_Use_of_Office_UNO_Components
         */    

        XComponentContext xCxt = com.sun.star.comp.helper.Bootstrap.bootstrap();
        /*ALTERNATIVE*/ //XComponentContext xCxt = BootstrapSocketConnector.bootstrap("C:/Program Files (x86)/LibreOffice 4/program/");

        XMultiComponentFactory xSMng = xCxt.getServiceManager();

        Object desk = xSMng.createInstanceWithContext("com.sun.star.frame.Desktop", xCxt);
        
        /* REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/OfficeDev/Using_the_Desktop */
        xDesk = UnoRuntime.queryInterface(XDesktop.class, desk);
        
        /** REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/Spreadsheets/Handling_Spreadsheet_Documents_Files#Creating_and_Loading_Spreadsheet_Documents
         *  REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/OfficeDev/Handling_Documents#Loading_Documents
         */
        XComponentLoader xCLoader =  (XComponentLoader)UnoRuntime.queryInterface(XComponentLoader.class, desk);                
        XComponent xDoc = xCLoader.loadComponentFromURL("private:factory/scalc", "_blank", 0, null);
        
        /** REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/OfficeDev/Component/Frames#Frame_Setup
         *  REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/OfficeDev/Creating_Frames_Manually#Frame_Creation
         */
        XFrame dFrame = xDesk.getCurrentFrame();
        while (dFrame == null) dFrame = xDesk.getCurrentFrame();

        XTitle wTitle = UnoRuntime.queryInterface(XTitle.class, dFrame);
        wTitle.setTitle(wTitle.getTitle().replace("Libre", "LIBRAS"));

        /* REF https://www.openoffice.org/api/docs/common/ref/com/sun/star/frame/XDispatchHelper.html */        
        Object disper = xSMng.createInstanceWithContext("com.sun.star.frame.DispatchHelper", xCxt);        
        xDHelper = UnoRuntime.queryInterface(XDispatchHelper.class, disper);
        /* REF https://wiki.openoffice.org/wiki/Documentation/DevGuide/OfficeDev/Dispatch_Results */
        xDProver = UnoRuntime.queryInterface(XDispatchProvider.class, dFrame);
        
        /*DEBUG*/ //xDHelper.executeDispatch(xDProver, ".uno:SaveAs", "", 0, null);
        
        /** REF http://api.libreoffice.org/examples/DevelopersGuide/OfficeDev/TerminationTest/TerminationTest.java 
         *  REF http://api.libreoffice.org/examples/DevelopersGuide/OfficeDev/TerminationTest/TerminateListener.java
         */
        xTL xTL0 = new xTL(); 
        xDesk.addTerminateListener(xTL0);
        synchronized(xTL0){
            try { xTL0.wait(); }
            catch (InterruptedException ex) {
                Logger.getLogger(LIBRASOffice.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABRIR;
    private javax.swing.JButton COLAR;
    private javax.swing.JButton COPIAR;
    private javax.swing.JButton CORTAR;
    private javax.swing.JPanel CampoFinal;
    private javax.swing.JPanel CampoInicial;
    private javax.swing.JPanel CampoResultado;
    private javax.swing.JButton DATA;
    private javax.swing.JButton DINHEIRO;
    private javax.swing.JButton DIVISAO;
    private javax.swing.JTextField Final;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JButton IMPRIMIR;
    private javax.swing.JTextField Inicial;
    private javax.swing.JLabel LabelFinal;
    private javax.swing.JLabel LabelInicial;
    private javax.swing.JLabel LabelResultado;
    private javax.swing.JButton MULTIPLICACAO;
    private javax.swing.JButton NOVO;
    private javax.swing.JButton NUMERO;
    private javax.swing.JButton NextFinal;
    private javax.swing.JButton NextInicial;
    private javax.swing.JButton NextResultado;
    private javax.swing.JButton PDF;
    private javax.swing.JButton PORCENTAGEM;
    private javax.swing.JButton PROCURAR;
    private javax.swing.JButton REFAZER;
    private javax.swing.JTextField Resultado;
    private javax.swing.JButton SOMAR;
    private javax.swing.JButton SUBTRACAO;
    private javax.swing.JButton VOLTAR;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    private static XDesktop xDesk;
    private static XDispatchHelper xDHelper;
    private static XDispatchProvider xDProver;
    private String currOpt = "FUNCAO";
    private Dimension scSize = Toolkit.getDefaultToolkit().getScreenSize();

    private void AssistenteFormula() {
        REFAZER.setVisible(false);
        VOLTAR.setVisible(false);
            jTabbedPane1.setVisible(false);
            CampoInicial.setVisible(true);
           jLabel1.setIcon(new ImageIcon(getClass().getResource("/GIF240/LOCAL_INICIAL_240.gif")));
    }
}